---
- name: create a vpc (public)
  ec2_vpc_net:
    name: public
    cidr_block: "{{ public_cidr_block }}"
    region: "{{ region }}"
    state: present
  register: vpc_public

- name: create a subnet (public)
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_public.vpc.id }}"
    cidr: "{{ public_cidr_block_a }}"
    az: "{{ az_a }}"
    tags:
      Name: public subnet A
    state: present

- name: create a subnet (public)
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_public.vpc.id }}"
    cidr: "{{ public_cidr_block_b }}"
    az: "{{ az_b }}"
    tags:
      Name: public subnet B
    state: present

- name: create a vpc (private)
  ec2_vpc_net:
    name: private
    cidr_block: "{{ private_cidr_block }}"
    region: "{{ region }}"
    state: present
  register: vpc_private

- name: create a subnet (private)
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_private.vpc.id }}"
    cidr: "{{ private_cidr_block_a }}"
    az: "{{ az_a }}"
    tags:
      Name: private subnet A
    state: present

- name: create a subnet (private)
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_private.vpc.id }}"
    cidr: "{{ private_cidr_block_b }}"
    az: "{{ az_b }}"
    tags:
      Name: private subnet B
    state: present

- name: create a vpc (isolated)
  ec2_vpc_net:
    name: isolated
    cidr_block: "{{ isolated_cidr_block }}"
    region: "{{ region }}"
    state: present
  register: vpc_isolated

- name: create a subnet (isolated)
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_isolated.vpc.id }}"
    cidr: "{{ isolated_cidr_block_a }}"
    az: "{{ az_a }}"
    tags:
      Name: isolated subnet A
    state: present

- name: create a subnet (isolated)
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_isolated.vpc.id }}"
    cidr: "{{ isolated_cidr_block_b }}"
    az: "{{ az_b }}"
    tags:
      Name: isolated subnet B
    state: present

- name: create a IGW
  ec2_vpc_igw:
    vpc_id: "{{ vpc_public.vpc.id }}"
    state: present

