---
- name: gether information about VPC
  ec2_vpc_net_info:
  register: vpc_info

- name: gather information about a DHCP options set
  ec2_vpc_dhcp_option_info:
    region: "{{ region }}"
  register: dhcp_info  

- name: gather information about IGW
  ec2_vpc_igw_info:
    region: "{{ region }}"
  register: igw_info

- name: delete a IGW
  ec2_vpc_igw:
    vpc_id: "{{ item.attachments[0].vpc_id }}"
    state: absent
  loop: "{{ igw_info.internet_gateways }}"

- name: delete subnets
  ec2_vpc_subnet:
    vpc_id: "{{ item.vpc_id }}"
    cidr: "{{ item.cidr_block }}"
    state: absent
  loop: "{{ vpc_info.vpcs }}"

- name: delete vpcs
  ec2_vpc_net:
    name: "{{ item.tags['Name'] }}"
    cidr_block: "{{ item.cidr_block }}"
    region: "{{ region }}"
    state: absent
  loop: "{{ vpc_info.vpcs }}"

- name: delete a DHCP options set
  ec2_vpc_dhcp_option:
    region: "{{ region }}"
    dhcp_options_id: "{{ item.dhcp_options_id }}"
    state: absent
  loop: "{{ dhcp_info.dhcp_options }}"  

