---
- name: gather information about VPC
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ lab_vpc_name }}"
  register: vpc_info

- name: gather information about subnet (public)
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      "tag:Type": public
  register: subnet_info_public

- name: gather information about subnet (private)
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      "tag:Type": private
  register: subnet_info_private

- name: security group for AP
  ec2_group:
    name: AP
    description: AP
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    state: present
    rules:
      - proto: tcp
        ports:
          - 443
          - 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports:
          - 22
          - 4369
          - 5672
          - 15672
          - 25672
          - 27199
        cidr_ip: "{{ public_cidr_block }}"
    tags:
      Name: AP
      Owner: "{{ owner }}"
  register: security_group_ap

- name: security group for DB
  ec2_group:
    name: DB
    description: DB
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    state: present
    rules:
      - proto: tcp
        ports:
          - 5432
          - 22
        cidr_ip: "{{ public_cidr_block }}"
    tags:
      Name: DB
      Owner: "{{ owner }}"
  register: security_group_db

- name: create a VM (AP)
  ec2_instance:
    instance_type: t3.medium
    region: "{{ region }}"
    image_id: "{{ ami_rhel84 }}"
    key_name: "{{ key }}"
    state: running
    wait: true
    termination_protection: false
    vpc_subnet_id: "{{ item.subnet_id }}"
    network:
      assign_public_ip: true
    security_group: "{{ security_group_ap.group_name }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 30
          volume_type: gp2
          delete_on_termination: true
    tags:
      Name: AP RHEL8
      Owner: "{{ owner }}"
  with_random_choice: "{{ subnet_info_public.subnets }}"

- name: create a VM (DB)
  ec2_instance:
    instance_type: t3.medium
    region: "{{ region }}"
    image_id: "{{ ami_rhel84 }}"
    key_name: "{{ key }}"
    state: running
    wait: true
    termination_protection: false
    vpc_subnet_id: "{{ item.subnet_id }}"
    network:
      assign_public_ip: true
    security_group: "{{ security_group_db.group_name }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 30
          volume_type: gp2
          delete_on_termination: true
    tags:
      Name: DB RHEL8
      Owner: "{{ owner }}"
  with_random_choice: "{{ subnet_info_private.subnets }}"

