---
- name: gather information about VPC
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ lab_vpc_name }}"
  register: vpc_info

- name: gather information about subnet
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      "tag:Type": public
  register: subnet_info

- name: find my public ip address
  uri:
    url: http://ifconfig.me/ip
    return_content: true
  register: my_ipaddress

- name: security group for SSH
  ec2_group:
    name: SSH
    description: SSH
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    state: present
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{ my_ipaddress.content }}/32"
    tags:
      Name: SSH
  register: security_group

- name: create a VM
  ec2:
    instance_type: t2.micro
    image: "{{ ami_rhel83 }}"
    wait: true
    assign_public_ip: true
    vpc_subnet_id: "{{ item.subnet_id }}"
    group_id: "{{ security_group.group_id }}"
    region: "{{ region }}"
    key_name: "{{ key }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 30
        volume_type: gp2
        delete_on_termination: true
    instance_tags:
      Name: bastion
  with_random_choice: "{{ subnet_info.subnets }}"
  
