---
- name: gather information about VPC
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ lab_vpc_name }}"
  register: vpc_info

- name: gather information about subnet
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      availability-zone: "{{ az_a }}"
      "tag:Type": public
  register: subnet_info

- name: find my public ip address
  uri:
    url: http://ifconfig.me/ip
    return_content: true
  register: my_ipaddress

- name: security group for SSH
  ec2_group:
    name: "{{ owner }} SSH"
    description: SSH
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    state: present
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{ my_ipaddress.content }}/32"
    tags:
      Name: "{{ owner }} SSH"
      Owner: "{{ owner }}"
  register: security_group

- name: create a VM
  ec2_instance:
    instance_type: t3.micro
    region: "{{ region }}"
    image_id: "{{ ami_rhel86 }}"
    key_name: "{{ key }}"
    state: running
    wait: true
    termination_protection: true
    vpc_subnet_id: "{{ subnet_info.subnets[0].subnet_id }}"
    network:
      assign_public_ip: true
    security_group: "{{ security_group.group_name }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 30
          volume_type: gp2
          delete_on_termination: true
    tags:
      Name: "{{ owner }} bastion"
      Owner: "{{ owner }}"
  
