---
- name: gather information about VPC
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ lab_vpc_name }}"
  register: vpc_info

- name: gather information about subnet (public)
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      "tag:Type": public
  register: subnet_info_public

- name: gather information about subnet (private)
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      "tag:Type": private
  register: subnet_info_private

- name: security group for AP
  ec2_group:
    name: AP
    description: AP
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    state: present
    rules:
      - proto: tcp
        ports:
          - 443
          - 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{ public_cidr_block }}"
    tags:
      Name: AP
  register: security_group_ap

- name: security group for DB
  ec2_group:
    name: DB
    description: DB
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    state: present
    rules:
      - proto: tcp
        ports:
          - 5432
          - 22
        cidr_ip: "{{ public_cidr_block }}"
    tags:
      Name: DB
  register: security_group_db

- name: create a VM (AP1)
  ec2:
    instance_type: t2.medium
    image: "{{ ami_rhel79 }}"
    wait: true
    assign_public_ip: true
    vpc_subnet_id: "{{ item.subnet_id }}"
    group_id: "{{ security_group_ap.group_id }}"
    region: "{{ region }}"
    key_name: "{{ key }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 30
        volume_type: gp2
    instance_tags:
      Name: "Cluster AP RHEL7 #1"
  with_random_choice: "{{ subnet_info_public.subnets }}"

- name: create a VM (AP2)
  ec2:
    instance_type: t2.medium
    image: "{{ ami_rhel79 }}"
    wait: true
    assign_public_ip: true
    vpc_subnet_id: "{{ item.subnet_id }}"
    group_id: "{{ security_group_ap.group_id }}"
    region: "{{ region }}"
    key_name: "{{ key }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 30
        volume_type: gp2
    instance_tags:
      Name: "Cluster AP RHEL7 #2"
  with_random_choice: "{{ subnet_info_public.subnets }}"

- name: create a VM (AP3)
  ec2:
    instance_type: t2.medium
    image: "{{ ami_rhel79 }}"
    wait: true
    assign_public_ip: true
    vpc_subnet_id: "{{ item.subnet_id }}"
    group_id: "{{ security_group_ap.group_id }}"
    region: "{{ region }}"
    key_name: "{{ key }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 30
        volume_type: gp2
    instance_tags:
      Name: "Cluster AP RHEL7 #3"
  with_random_choice: "{{ subnet_info_public.subnets }}"

- name: create a VM (DB)
  ec2:
    instance_type: t2.medium
    image: "{{ ami_rhel79 }}"
    wait: true
    assign_public_ip: false
    vpc_subnet_id: "{{ item.subnet_id }}"
    group_id: "{{ security_group_db.group_id }}"
    region: "{{ region }}"
    key_name: "{{ key }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 30
        volume_type: gp2
    instance_tags:
      Name: "Cluster DB RHEL7"
  with_random_choice: "{{ subnet_info_private.subnets }}"
  
