---
- name: gather information about VPC
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ isolated_vpc_name }}"
  register: vpc_info

- name: gather information about subnet
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      "tag:Type": isolated
  register: subnet_info

- name: security group for isolated
  ec2_group:
    name: isolated
    description: isolated (22/tcp)
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    state: present
    rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: "{{ public_cidr_block }}"
    tags:
      Name: isolated
  register: security_group

- name: create a VM
  ec2:
    instance_type: t2.medium
    image: "{{ ami_rhel79 }}"
    wait: true
    assign_public_ip: false
    vpc_subnet_id: "{{ item.subnet_id }}"
    group_id: "{{ security_group.group_id }}"
    region: "{{ region }}"
    key_name: "{{ key }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 30
        volume_type: gp2
        delete_on_termination: true
    instance_tags:
      Name: isolated RHEL7
  with_random_choice: "{{ subnet_info.subnets }}"
  
