---
- name: gather information about VPC
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ isolated_vpc_name }}"
  register: vpc_info

- name: gather information about subnet
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      "tag:Type": isolated
  register: subnet_info

- name: security group for isolated
  ec2_group:
    name: isolated RHEL8
    description: isolated and receptor (22/tcp, 27199/tcp)
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    state: present
    rules:
      - proto: tcp
        ports:
          - 22
          - 27199
        cidr_ip: "{{ public_cidr_block }}"
    tags:
      Name: isolated RHEL8
      Owner: "{{ owner }}"
  register: security_group

- name: create a VM
  ec2_instance:
    instance_type: t3.medium
    region: "{{ region }}"
    image_id: "{{ ami_rhel86 }}"
    key_name: "{{ key }}"
    state: running
    wait: true
    termination_protection: false
    vpc_subnet_id: "{{ item.subnet_id }}"
    network:
      assign_public_ip: false
    security_group: "{{ security_group.group_name }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 30
          volume_type: gp2
          delete_on_termination: true
    tags:
      Name: "isolated RHEL8"
      Owner: "{{ owner }}"
  with_random_choice: "{{ subnet_info.subnets }}"

