---
- name: gather information about VPC
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ lab_vpc_name }}"
  register: vpc_info

- name: gather information about subnet
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      "tag:Type": public
  register: subnet_info

- name: security group for AP
  ec2_group:
    name: AP
    description: AP
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    state: present
    rules:
      - proto: tcp
        ports:
          - 443
          - 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports:
          - 22
          - 4369
          - 5672
          - 15672
          - 25672
        cidr_ip: "{{ public_cidr_block }}"
    tags:
      Name: AP
      Owner: "{{ owner }}"
  register: security_group

- name: create a VM
  ec2:
    instance_type: t2.medium
    image: "{{ ami_rhel84 }}"
    wait: true
    assign_public_ip: true
    vpc_subnet_id: "{{ item.subnet_id }}"
    group_id: "{{ security_group.group_id }}"
    region: "{{ region }}"
    key_name: "{{ key }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 30
        volume_type: gp2
        delete_on_termination: true
    instance_tags:
      Name: standalone RHEL8
      Owner: "{{ owner }}"
  with_random_choice: "{{ subnet_info.subnets }}"
  
