---
- name: gather information about VPC
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ lab_vpc_name }}"
  register: vpc_info

- name: gather information about subnet
  ec2_vpc_subnet_info:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_info.vpcs[0].id }}"
      "tag:Type": private
  register: subnet_info

- name: security group for Windows
  ec2_group:
    name: Windows
    description: Windows
    region: "{{ region }}"
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
    state: present
    rules:
      - proto: tcp
        ports:
          - 3389
          - 5985
          - 5986
        cidr_ip: "{{ public_cidr_block }}"
    tags:
      Name: Windows
      Owner: "{{ owner }}"
  register: security_group

- name: create a VM
  ec2:
    instance_type: t2.medium
    image: "{{ ami_win2019 }}"
    wait: true
    assign_public_ip: false
    vpc_subnet_id: "{{ item.subnet_id }}"
    group_id: "{{ security_group.group_id }}"
    region: "{{ region }}"
    key_name: "{{ key }}"
    user_data: "{{ lookup('file', 'init.ps1') }}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 30
        volume_type: gp2
        delete_on_termination: true
    instance_tags:
      Name: Windows 2019
      Owner: "{{ owner }}"
  with_random_choice: "{{ subnet_info.subnets }}"

