---
- name: gather information about VPC
  ec2_vpc_net_info:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ lab_vpc_name }}"
  register: vpc_info

- name: gather information about security group
  ec2_group_info:
    region: "{{ region }}"
    filters:
      "tag:Owner": "{{ owner }}"
  register: group_info

- name: gather information about instances
  ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:Owner": "{{ owner }}"
  register: instance_info

- name: remove VMs
  ec2:
    state: absent
    wait: true
    region: "{{ region }}"
    instance_ids: "{{ item.instance_id }}"
  loop: "{{ instance_info.instances }}"
  ignore_errors: true

- name: gather information about target groups
  elb_target_group_info:
    region: "{{ region }}"
  register: target_group_info

- name: gather information about Application load balancers
  elb_application_lb_info:
    region: "{{ region }}"
  register: alb_info

- name: remove Application load balancers
  elb_application_lb:
    state: absent
    region: "{{ region }}"
    name: "{{ item.load_balancer_name }}"
    wait: true
  loop: "{{ alb_info.load_balancers }}"

- name: remove target groups
  elb_target_group:
    state: absent
    name: "{{ item.target_group_name }}"
    protocol: http
    port: 80
    vpc_id: "{{ vpc_info.vpcs[0].id }}"
  loop: "{{ target_group_info.target_groups }}"

- name: remove security groups
  ec2_group:
    state: absent
    region: "{{ region }}"
    group_id: "{{ item.group_id }}"
  loop: "{{ group_info.security_groups }}"
  ignore_errors: true

